### ISSUE TITLE
  java.lang.RuntimeException: stop failed.

### ISSUE THREAD

**Issue by werbhelius** [changer0/WeiChatSampleVideo#1]
FATAL EXCEPTION: main
                                                                           Process: com.lulu.weichatsamplevideo, PID: 8102
                                                                           java.lang.RuntimeException: stop failed.
                                                                               at android.media.MediaRecorder.stop(Native Method)
                                                                               at com.lulu.weichatsamplevideo.MainActivity.stopRecordSave(MainActivity.java:244)
                                                                               at com.lulu.weichatsamplevideo.MainActivity.onTouch(MainActivity.java:386)
                                                                               at android.view.View.dispatchTouchEvent(View.java:9300)
                                                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2548)
                                                                               at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2241)
                                                                               at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)

**Comment by werbhelius** [comment]
解决了...
自己写了一个小例子...
https://github.com/Werb/MediaUtils
